services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
      - ./:/var/www/html
    depends_on:
      - mysql
      - redis
      - mailhog
      - server


  server:
    container_name: server
    build:
      context: .
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql
      - redis
      - mailhog

  mysql:
    container_name: mysql
    image: mysql:5.7.22
    restart: unless-stopped
    environment:
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        MYSQL_PASSWORD: ${DB_PASSWORD}
        MYSQL_USER: ${DB_USERNAME}
    volumes:
        - ./src/data/initialData.sql:/docker-entrypoint-initdb.d/initialData.sql
    ports:
        - 3388:3306


  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
      
  mailhog:
    container_name: mailhog
    image: mailhog/mailhog:latest
    ports:
      - 1025:1025
      - 8025:8025