version: '3.8'
services:
  # db mysql
  db:
    container_name: mysql
    image: mysql:5.7.22
    restart: unless-stopped
    environment:
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        MYSQL_PASSWORD: ${DB_PASSWORD}
        MYSQL_USER: ${DB_USERNAME}
    volumes:
        - ./database/SQLProjetoLab.sql:/docker-entrypoint-initdb.d/SQLProjetoLab.sql
    ports:
        - "3388:3306"
    networks:
        - labProg

  php:
    container_name: php
    image: webdevops/php-nginx
    restart: always
    ports:
      - 9999:80
    volumes:
      - .:/app
    networks:
      - labProg
    depends_on: 
      - db  

networks:
  labProg: